# Generated by Django 5.1.15 on 2026-07-23 21:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_calcul', models.CharField(choices=[('terrassement', 'Terrassement'), ('gros_oeuvre', 'Gros œuvre'), ('cloison', 'Cloison'), ('finition', 'Finition'), ('electricite', 'Électricité')], max_length=30)),
                ('phase', models.CharField(choices=[('terrassement', 'Terrassement'), ('fondation', 'Fondation'), ('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition')], max_length=30)),
                ('parametres', models.JSONField()),
                ('resultats', models.JSONField()),
                ('reference_normative', models.CharField(blank=True, max_length=200)),
                ('coefficient_perte', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=200)),
                ('date_devis', models.DateField()),
                ('devise_code', models.CharField(max_length=3)),
                ('taux_conversion', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('statut', models.CharField(default='brouillon', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbole', models.CharField(max_length=10)),
                ('taux_conversion', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('unite', models.CharField(max_length=20)),
                ('prix_unitaire_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coefficient_perte_defaut', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('terrassement', 'Terrassement'), ('fondation', 'Fondation'), ('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition')], max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='plans/')),
                ('image_url', models.URLField(blank=True)),
                ('echelle_metres_par_pixel', models.FloatField(blank=True, null=True)),
                ('etalonnage_valide', models.BooleanField(default=False)),
                ('analyse_ia_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatioFerraillage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_ouvrage', models.CharField(max_length=50)),
                ('ratio_acier_kg_par_m3', models.FloatField()),
                ('reference_normative', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nature_sol', models.CharField(max_length=100)),
                ('coefficient_foisonnement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_abonne', models.BooleanField(default=False)),
                ('abonnement_expiration', models.DateTimeField(blank=True, null=True)),
                ('cgu_acceptees', models.BooleanField(default=False)),
                ('cgu_date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=300)),
                ('phase', models.CharField(choices=[('terrassement', 'Terrassement'), ('fondation', 'Fondation'), ('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition')], max_length=30)),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unite', models.CharField(max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('coefficient_perte', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('ordre', models.PositiveIntegerField()),
                ('calcul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calcul_btp.calcul')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='calcul_btp.devis')),
            ],
        ),
        migrations.CreateModel(
            name='ElementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_element', models.CharField(choices=[('mur', 'Mur'), ('ouverture', 'Ouverture'), ('cote', 'Cote'), ('surface', 'Surface')], max_length=20)),
                ('geometrie', models.JSONField()),
                ('valeur_metres', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_valide', models.BooleanField(default=True)),
                ('statut_validation', models.CharField(default='propose', max_length=30)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='calcul_btp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('adresse_chantier', models.TextField(blank=True)),
                ('nom_client', models.CharField(blank=True, max_length=200)),
                ('devise_code', models.CharField(default='XOF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='calcul_btp.projet'),
        ),
        migrations.AddField(
            model_name='devis',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='calcul_btp.projet'),
        ),
        migrations.AddField(
            model_name='calcul',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs', to='calcul_btp.projet'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['utilisateur', '-updated_at'], name='calcul_btp__utilisa_16c45e_idx'),
        ),
        migrations.AddIndex(
            model_name='calcul',
            index=models.Index(fields=['projet', '-created_at'], name='calcul_btp__projet__d84a19_idx'),
        ),
    ]
